version: '3.5'

services:
    whisper:
        hostname: whisper
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: 1
                            capabilities: [ gpu ]
